Traceback (most recent call last):
  File "A3_4.py", line 58, in <module>
    m.create_model_routing(mipfocus=1,timelimit=time_limit_routing,mipgap=0.01, method=2)
  File "/local/tmp.1046305/sdm.py", line 1414, in create_model_routing
    chout = core_choicex[u,u[0]]
KeyError: ((1, 42), 1)
